In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('C:\\Users\\koriv\\Desktop\\MachineLearning_DataScience\\Hands_On_Machine_Learning\\2_linear_reg_multivariate\\homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
## Data Preprocessing: Fill NA values with median value of a column

In [4]:
df.bedrooms.median()

4.0

In [10]:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms # rounding the median to the nearest value

4

In [12]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df.bedrooms

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [13]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price) # or reg.fit(df[[area, bedrooms, age]],df.price)

LinearRegression()

In [15]:
reg.coef_ #slopes of the features

array([  112.06244194, 23388.88007794, -3231.71790863])

In [16]:
reg.intercept_ # constant or intercept

221323.00186540443

In [21]:
reg.predict([[3000, 3, 40]]) # Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old

array([498408.25158031])

In [23]:
# Excersice to figure out salary given experice, test score and interview score

In [53]:
df = pd.read_csv('C:\\Users\\koriv\\Desktop\\MachineLearning_DataScience\\Hands_On_Machine_Learning\\2_linear_reg_multivariate\\hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [54]:
## Data Preprocessing: Fill NA values with median value of a column

In [55]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\users\koriv\desktop\machinelearning_datascience\hands_on_machine_learning\my_env\scripts\python.exe -m pip install --upgrade pip' command.


In [56]:
df.columns = df.columns.str.replace(' ','_')
df.columns = df.columns.str.replace('$','')
df.columns = df.columns.str.replace(')','')
df.columns = df.columns.str.replace('(','')
df

C:\Users\koriv\AppData\Local\Temp/ipykernel_15836/1070797532.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df.columns = df.columns.str.replace('$','')
C:\Users\koriv\AppData\Local\Temp/ipykernel_15836/1070797532.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df.columns = df.columns.str.replace(')','')
C:\Users\koriv\AppData\Local\Temp/ipykernel_15836/1070797532.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df.columns = df.columns.str.replace('(','')


experience  test_scoreout_of_10  interview_scoreout_of_10  salary
0        NaN                  8.0                         9   50000
1        NaN                  8.0                         6   45000
2       five                  6.0                         7   60000
3        two                 10.0                        10   65000
4      seven                  9.0                         6   70000
5      three                  7.0                        10   62000
6        ten                  NaN                         7   72000
7     eleven                  7.0                         8   80000

In [58]:
from word2number import w2n
df.experience = df.experience.fillna("zero") #filling null values in the experience column to zero
df.experience = df.experience.apply(w2n.word_to_num) #converting string to number
df

experience  test_scoreout_of_10  interview_scoreout_of_10  salary
0           0                  8.0                         9   50000
1           0                  8.0                         6   45000
2           5                  6.0                         7   60000
3           2                 10.0                        10   65000
4           7                  9.0                         6   70000
5           3                  7.0                        10   62000
6          10                  NaN                         7   72000
7          11                  7.0                         8   80000

In [60]:
import math
median_test_score = math.floor(df.test_scoreout_of_10.median())
median_test_score

8

In [61]:
df.test_scoreout_of_10 = df.test_scoreout_of_10.fillna(median_test_score)
df

experience  test_scoreout_of_10  interview_scoreout_of_10  salary
0           0                  8.0                         9   50000
1           0                  8.0                         6   45000
2           5                  6.0                         7   60000
3           2                 10.0                        10   65000
4           7                  9.0                         6   70000
5           3                  7.0                        10   62000
6          10                  8.0                         7   72000
7          11                  7.0                         8   80000

In [63]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience', 'test_scoreout_of_10', 'interview_scoreout_of_10']],df.salary) # or reg.fit(df[[area, bedrooms, age]],df.price)

LinearRegression()

In [64]:
reg.coef_ #slopes of the features

array([2812.95487627, 1845.70596798, 2205.24017467])

In [65]:
reg.intercept_ # constant or intercept

17737.263464337695

In [68]:
reg.predict([[2, 9, 6]]) # Find salary of employee with 2 years experience, 9 test score and 6 interveiw score

array([53205.96797671])

In [69]:
reg.predict([[12, 10, 10]]) # Find salary of employee with 12 years experience, 10 test score and 10 interveiw score

array([92002.18340611])