In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

#### Logistic Regression

In [4]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9648148148148148

#### SVM

In [5]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.39444444444444443

#### Random Forest

In [7]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9777777777777777

## KFold cross validation
### Basic

In [76]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [77]:
for train_index, test_index in kf.split([0,1,2,3,4,5,6,7,8,9], [1,0,1,0,1,0,1,1,1,1]):
    #print("value: %s, %s, %s, %s"%(X_train[train_index], y_train[train_index], X_train[test_index], y_train[test_index]))
    print("Index: %s, %s"%(train_index, test_index))

Index: [4 5 6 7 8 9], [0 1 2 3]
Index: [0 1 2 3 7 8 9], [4 5 6]
Index: [0 1 2 3 4 5 6], [7 8 9]


In [74]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)
skf

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [75]:
for train_index, test_index in skf.split([0,1,2,3,4,5,6,7,8,9], [1,0,1,0,1,0,1,1,1,1]):
    #print(X_train[train_index], y_train[train_index], X_train[test_index], y_train[test_index])
    print("Index: %s, %s"%(train_index, test_index))

Index: [3 5 6 7 8 9], [0 1 2 4]
Index: [0 1 2 4 5 8 9], [3 6 7]
Index: [0 1 2 3 4 6 7], [5 8 9]


## Use KFold(Stratified) for our digits example

In [64]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [65]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [66]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [67]:
print(scores_logistic)
print(scores_svm)
print(scores_rf)

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]
[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]
[0.9315525876460768, 0.9398998330550918, 0.9282136894824707]


## Using cross_val_score function

In [78]:
from sklearn.model_selection import cross_val_score

In [81]:
# Logistic regression model performance using cross_val_score
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [80]:
# svm model performance using cross_val_score
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [82]:
# random forest performance using cross_val_score
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92988314, 0.94657763, 0.9148581 ])

## Parameter tunning using k fold cross validation

In [83]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.876455617628802

In [84]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9371135940409683

In [85]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.943792675356921

In [86]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.951024208566108